on:
  push:
    branches: [ release/* ]

jobs:
  build:
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: src/PsDac/bin/Debug/net5.0/publish