on:
  push:
    branches: [ release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: src/PsCosmos/bin/Debug/net5.0/publish