on:
  push:
    branches: [ release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build -Configuration Release

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: src/PsCosmos/bin/Debug/net5.0/publish

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          repo: ${{github.repository}}
          name: artifact
          path: publish/

      - name: Publish to PsGallery
        shell: pwsh
        run: |
          $Manifest = Get-Item publish/PsCosmos.psd1
          $ModuleName = $Manifest.BaseName
          $Info = Import-PowerShellDataFile $Manifest
          Publish-Module -Name $ModuleName -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}
